# Generated by Django 5.2.6 on 2025-10-06 02:34

import ia.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_documento_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='embeddingdocumento',
            index=ia.indexes.BM25Index(fields=['id', 'conteudo'], name='ia_embeddin_id_fd93c1_bm25'),
        ),
    ]
