# Generated by Django 5.2.6 on 2025-10-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0007_embeddingdocumento_ia_embeddin_id_fd93c1_bm25'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='embeddingdocumento',
            new_name='bm25_index_conteudo',
            old_name='ia_embeddin_id_fd93c1_bm25',
        ),
    ]
